language: python
services:
  - redis-server
python:
  - "2.6"
  - "2.7"
env:
  - DATABASE="sqlite3"
  - DATABASE="postgresql"
install: "pip install -r dev-requirements.txt --use-mirrors"
before_script:
  - psql -c 'CREATE DATABASE djac;' -U postgres
script: make test
